export type { IHitbox, HitboxEngineContext, HitboxPreviewCaster } from './Hitbox';
export { Hitbox } from './Hitbox';
export { ThickLineHitbox } from './ThickLineHitbox';
export { CircleHitbox, unitOverlapsCircle } from './CircleHitbox';
export { HitboxSpec, MeleeLineHitboxSpec, meleeLineHitbox, PerpendicularSwingHitboxSpec, perpendicularSwingHitbox, NullHitboxSpec, nullHitbox } from './HitboxSpec';
export { UnitRangeHitboxSpec, unitRangeHitbox } from './UnitRangeHitboxSpec';
export { CircleAoEHitboxSpec, circleAoEHitbox, type CircleAoEPreviewStyle } from './CircleAoEHitboxSpec';
export { TruncatedConeHitboxSpec, type TruncatedConeGeometry, type TruncatedConeMinRadiusResolver } from './TruncatedConeHitbox';
export { ConvexQuadHitboxSpec, convexQuadHitbox } from './ConvexQuadHitbox';
export { SquareTileAreaHitboxSpec, squareTileAreaHitbox, type SquareTileAreaPreviewStyle } from './SquareTileAreaHitboxSpec';
